name = "gemini-app"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB"
database_name = "history_db"
database_id = "c8a5f1cb-c69f-4bd6-a2b2-ac95574af106" 
